version: '3'

services:
  ngnix:
    build: ./requirements/nginx/.
    container_name: ngnix
    ports:
      - "443:443"
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.

  